name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js for Angular
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install Angular dependencies and build
      run: |
        cd Frontend
        npm install
        npm run build

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Flask dependencies
      run: pip install -r Backend/requirements.txt

    - name: Run Flask tests
      run: |
        cd Backend
        pytest tests